spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/timesheetdb
    username: user
    password: password
    driver: com.mysql.jdbc.Driver