spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver: org.postgresql.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: studintinc@gmail.com
    password: Bu$ine$$
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true